[package]
name = "rhosql"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["rhosql-macros"]

[dependencies]
libsqlite3-sys = "0.32.0"
rhosql-macros = { version = "0.1.0", path = "rhosql-macros" }

[features]
bundled = ["libsqlite3-sys/bundled"]

